id: P009409
initial_creation_type: ocr
source_metadata:
  id: bdr:W3PD188
  title: གསུང་འབུམ། ཙོང་ཁ་པ།
  author: ''
  volumes:
    8ec0db74168d45ffaaa331973b0e07cd:
      image_group_id: I3PD266
      title: ''
      volume_number: 1
      total_pages: 788
      base_file: v001.txt
    97ca1a2f644a403e9f33f09403447969:
      image_group_id: I3PD267
      title: ''
      volume_number: 2
      total_pages: 742
      base_file: v002.txt
    a92f807349564853813811dc823cd78b:
      image_group_id: I3PD268
      title: ''
      volume_number: 3
      total_pages: 792
      base_file: v003.txt
    ac24c2a1d3044e44b6c940d1644a2c31:
      image_group_id: I3PD269
      title: ''
      volume_number: 4
      total_pages: 842
      base_file: v004.txt
    3dde54f5e35a4cd5ae8172ee810cc5a8:
      image_group_id: I3PD270
      title: ''
      volume_number: 5
      total_pages: 690
      base_file: v005.txt
    acc1982a09794346b08e7022d51bb4a0:
      image_group_id: I3PD271
      title: ''
      volume_number: 6
      total_pages: 646
      base_file: v006.txt
    ab5c059bdca54ecebb8b63375d808884:
      image_group_id: I3PD272
      title: ''
      volume_number: 7
      total_pages: 658
      base_file: v007.txt
    19e4bf45dfc44a4cb544de9b80f2efe8:
      image_group_id: I3PD273
      title: ''
      volume_number: 8
      total_pages: 722
      base_file: v008.txt
    6c0584d267324c8a8e25fed6de844c94:
      image_group_id: I3PD274
      title: ''
      volume_number: 9
      total_pages: 698
      base_file: v009.txt
    035d8404c75941a3a53e268ba3872d53:
      image_group_id: I3PD275
      title: ''
      volume_number: 10
      total_pages: 680
      base_file: v010.txt
    6238cebe93dc4013ac79b00057353346:
      image_group_id: I3PD276
      title: ''
      volume_number: 11
      total_pages: 658
      base_file: v011.txt
    af37bbb757114d54ad65decb7a7d93d7:
      image_group_id: I3PD277
      title: ''
      volume_number: 12
      total_pages: 657
      base_file: v012.txt
    56923382541f4264ba4fb2a1c02e86f5:
      image_group_id: I3PD278
      title: ''
      volume_number: 13
      total_pages: 842
      base_file: v013.txt
    64ee59df8f0f4cd0bd4d63d487e0c9c7:
      image_group_id: I3PD279
      title: ''
      volume_number: 14
      total_pages: 758
      base_file: v014.txt
    e25d330533db4e50bb0b6c1bb191efa0:
      image_group_id: I3PD280
      title: ''
      volume_number: 15
      total_pages: 682
      base_file: v015.txt
    a2ba745f3b8347d9bf813cfa435e75e8:
      image_group_id: I3PD281
      title: ''
      volume_number: 16
      total_pages: 706
      base_file: v016.txt
    c155bf70c0fe40b3be155db8ae171a8b:
      image_group_id: I3PD282
      title: ''
      volume_number: 17
      total_pages: 694
      base_file: v017.txt
    2acd547aae9f41b7be94cb4d800cbfab:
      image_group_id: I3PD283
      title: ''
      volume_number: 18
      total_pages: 742
      base_file: v018.txt
